### ISSUE TITLE
Show error message instead of just saying "Error occurred " in Rails log

### ISSUE THREAD

**Issue by ryreitsma** [BUS-OGD/arrthorizer#37]
When writing new Arrthorizer roles, I make silly mistakes like undefined variables. If I run a server, the log then just shows 'Error occurred while evaluating Folders::FolderOwner for #<User:0x00000009cbafd0>'. That doesn't help much, I cannot see which error occurred!

I'd like to see the error message in the Rails log, because if it's included, you'd easily spot my silly mistake:
'Error occurred while evaluating  Folders::FolderOwner for #<User:0x000000098a8320>: undefined local variable or method `folder' for #< Folders::FolderOwner:0x000000097a9730>'

**Comment by ReneB** [comment]
I'll just write out a stacktrace at the `debug` level then. Sounds plausible. When you're writing new roles, you're probably in "development" Rails env, which, by default, logs `debug` level as well, but it won't pollute your logs otherwise.
